Repository whymog/efjm, pull requests merged in 2018-09, with the labels that each got.

#55 Remove repeated 20XX year refs in Mom's Tent
  src/s2a_moms_tent.tw2
Labels: enhancement

#56 Update README
  README.md
Labels: chore

#57 Fix: Extra "I" in a sentence
  src/s2b_tent_city_chase.tw2
Labels: bug

#62 added new scenes after you walk away from Dopeman Dan
  src/s3b_the_roach_market.tw2
Labels: enhancement

#67 Add readme image
  README.md
Labels: enhancement
